In [46]:
import pandas as pd
df= pd.read_csv('data/titanic2.csv')
df.head()

,PassengerId,Name,Pclass,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,Survived
0,1,"Braund, Mr. Owen Harris",3,male,22.0,1,0,A/5 21171,7.2500,NaN,S,0
1,2,"Cumings, Mrs. John Bradley (Florence Briggs Th...",1,female,38.0,1,0,PC 17599,71.2833,C85,C,1
2,3,"Heikkinen, Miss. Laina",3,female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S,1
3,4,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",1,female,35.0,1,0,113803,53.1000,C123,S,1
4,5,"Allen, Mr. William Henry",3,male,35.0,0,0,373450,8.0500,NaN,S,0

In [47]:
df.drop(['PassengerId', 'Name', 'SibSp', 'Parch', 'Ticket', 'Cabin', 'Embarked'], axis='columns', inplace=True)
df.head()

   Pclass     Sex   Age     Fare  Survived
0       3    male  22.0   7.2500         0
1       1  female  38.0  71.2833         1
2       3  female  26.0   7.9250         1
3       1  female  35.0  53.1000         1
4       3    male  35.0   8.0500         0

In [48]:
target = df.Survived
target

0      0
1      1
2      1
3      1
4      0
      ..
886    0
887    1
888    0
889    1
890    0
Name: Survived, Length: 891, dtype: int64

In [49]:
inputs = df.drop(['Survived'], axis='columns')
inputs

     Pclass     Sex   Age     Fare
0         3    male  22.0   7.2500
1         1  female  38.0  71.2833
2         3  female  26.0   7.9250
3         1  female  35.0  53.1000
4         3    male  35.0   8.0500
..      ...     ...   ...      ...
886       2    male  27.0  13.0000
887       1  female  19.0  30.0000
888       3  female   NaN  23.4500
889       1    male  26.0  30.0000
890       3    male  32.0   7.7500

[891 rows x 4 columns]

In [50]:
dummies = pd.get_dummies(inputs.Sex)
bool_cols = dummies.select_dtypes(include="bool").columns
dummies[bool_cols] = dummies[bool_cols].astype(int)
dummies

     female  male
0         0     1
1         1     0
2         1     0
3         1     0
4         0     1
..      ...   ...
886       0     1
887       1     0
888       1     0
889       0     1
890       0     1

[891 rows x 2 columns]

In [51]:
inputs = pd.concat([inputs, dummies], axis='columns')
inputs.head()

   Pclass     Sex   Age     Fare  female  male
0       3    male  22.0   7.2500       0     1
1       1  female  38.0  71.2833       1     0
2       3  female  26.0   7.9250       1     0
3       1  female  35.0  53.1000       1     0
4       3    male  35.0   8.0500       0     1

In [52]:
inputs.drop('Sex', axis='columns', inplace=True)
inputs

     Pclass   Age     Fare  female  male
0         3  22.0   7.2500       0     1
1         1  38.0  71.2833       1     0
2         3  26.0   7.9250       1     0
3         1  35.0  53.1000       1     0
4         3  35.0   8.0500       0     1
..      ...   ...      ...     ...   ...
886       2  27.0  13.0000       0     1
887       1  19.0  30.0000       1     0
888       3   NaN  23.4500       1     0
889       1  26.0  30.0000       0     1
890       3  32.0   7.7500       0     1

[891 rows x 5 columns]

In [53]:
inputs.columns[inputs.isna().any()]

Index(['Age'], dtype='object')

In [54]:
inputs.Age[:10]

0    22.0
1    38.0
2    26.0
3    35.0
4    35.0
5     NaN
6    54.0
7     2.0
8    27.0
9    14.0
Name: Age, dtype: float64

In [55]:
mean_age = round(inputs.Age.mean())
inputs.Age = inputs.Age.fillna(mean_age)
inputs.Age[:10]

0    22.0
1    38.0
2    26.0
3    35.0
4    35.0
5    30.0
6    54.0
7     2.0
8    27.0
9    14.0
Name: Age, dtype: float64

In [56]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(inputs,target, test_size=0.2)
len(x_train)

712

In [57]:
len(x_test)

179

In [58]:
len(inputs)

891

In [59]:
from sklearn.naive_bayes import GaussianNB
model = GaussianNB()
model.fit(x_train,y_train)

GaussianNB()

In [60]:
model.score(x_test,y_test)

0.7988826815642458

In [61]:
x_test[:10]

     Pclass   Age     Fare  female  male
359       3  30.0   7.8792       1     0
109       3  30.0  24.1500       1     0
63        3   4.0  27.9000       0     1
227       3  20.5   7.2500       0     1
813       3   6.0  31.2750       1     0
656       3  30.0   7.8958       0     1
33        2  66.0  10.5000       0     1
90        3  29.0   8.0500       0     1
881       3  33.0   7.8958       0     1
112       3  22.0   8.0500       0     1

In [62]:
y_test[:10]

359    1
109    1
63     0
227    0
813    0
656    0
33     0
90     0
881    0
112    0
Name: Survived, dtype: int64

In [63]:
model.predict(x_test[:10])

array([1, 1, 0, 0, 1, 0, 0, 0, 0, 0])

In [64]:
model.predict_proba(x_test[:10])

array([[0.05313403, 0.94686597],
       [0.05298714, 0.94701286],
       [0.9770884 , 0.0229116 ],
       [0.98793941, 0.01206059],
       [0.02430338, 0.97569662],
       [0.99015542, 0.00984458],
       [0.97374904, 0.02625096],
       [0.99001339, 0.00998661],
       [0.9905338 , 0.0094662 ],
       [0.9884725 , 0.0115275 ]])

Part 2

In [65]:
import pandas as pd
df = pd.read_csv('data/spam.csv')
df.head()

  Category                                            Message
0      ham  Go until jurong point, crazy.. Available only ...
1      ham                      Ok lar... Joking wif u oni...
2     spam  Free entry in 2 a wkly comp to win FA Cup fina...
3      ham  U dun say so early hor... U c already then say...
4      ham  Nah I don't think he goes to usf, he lives aro...

In [66]:
df.groupby('Category').describe()

         Message                                                            \
           count unique                                                top
Category
ham         4825   4516                             Sorry, I'll call later
spam         747    641  Please call our customer service representativ...


         freq
Category
ham        30
spam        4

In [67]:
df['spam'] = df['Category'].apply(lambda x:1 if x == 'spam' else 0)
df.drop(['Category'], axis='columns', inplace=True)
df

                                                Message  spam
0     Go until jurong point, crazy.. Available only ...     0
1                         Ok lar... Joking wif u oni...     0
2     Free entry in 2 a wkly comp to win FA Cup fina...     1
3     U dun say so early hor... U c already then say...     0
4     Nah I don't think he goes to usf, he lives aro...     0
...                                                 ...   ...
5567  This is the 2nd time we have tried 2 contact u...     1
5568               Will ü b going to esplanade fr home?     0
5569  Pity, * was in mood for that. So...any other s...     0
5570  The guy did some bitching but I acted like i'd...     0
5571                         Rofl. Its true to its name     0

[5572 rows x 2 columns]

In [68]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(df.Message, df.spam, test_size=0.25)
x_train

2686    URGENT! We are trying to contact U. Todays dra...
3588    Our ride equally uneventful - not too many of ...
1324    I thk 50 shd be ok he said plus minus 10.. Did...
184                              He will, you guys close?
4739    I bought the test yesterday. Its something tha...
                              ...
4146    Lol I would but despite these cramps I like be...
2601       As usual..iam fine, happy &amp; doing well..:)
3564    Auction round 4. The highest bid is now £54. N...
1179    I'm outside islands, head towards hard rock an...
3601                            I know you mood off today
Name: Message, Length: 4179, dtype: object

In [69]:
from sklearn.feature_extraction.text import CountVectorizer
c = CountVectorizer()
x_train_count = c.fit_transform(x_train.values)
x_train_count.toarray()[:3]

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]], shape=(3, 7510))

In [70]:
from sklearn.naive_bayes import MultinomialNB
model = MultinomialNB()
model.fit(x_train_count,y_train)

MultinomialNB()

In [71]:
emails = [
    'Hey mohan, can we get together to watch football tomorrow?',
    'Up to 20% discount on parking , exclusive offer just for you. Dont miss this reward!'
]
emails_count = c.transform(emails)
model.predict(emails_count)

array([0, 1])

In [72]:
x_train_count = c.transform(x_test)
model.score(x_train_count, y_test)

0.9885139985642498

In [73]:
from sklearn.pipeline import Pipeline
clf = Pipeline([
    ('vectorizer', CountVectorizer()),
    ('nb', MultinomialNB())
])

In [74]:
clf.fit(x_train, y_train)

Pipeline(steps=[('vectorizer', CountVectorizer()), ('nb', MultinomialNB())])

In [75]:
clf.score(x_test, y_test)

0.9885139985642498

In [76]:
clf.predict(emails)

array([0, 1])

Exercise

In [77]:
from sklearn.datasets import load_wine
wine = load_wine()
df = pd.DataFrame(wine.data, columns=wine.feature_names)
df.head()

,alcohol,malic_acid,ash,alcalinity_of_ash,magnesium,total_phenols,flavanoids,nonflavanoid_phenols,proanthocyanins,color_intensity,hue,od280/od315_of_diluted_wines,proline
0,14.23,1.71,2.43,15.6,127.0,2.80,3.06,0.28,2.29,5.64,1.04,3.92,1065.0
1,13.20,1.78,2.14,11.2,100.0,2.65,2.76,0.26,1.28,4.38,1.05,3.40,1050.0
2,13.16,2.36,2.67,18.6,101.0,2.80,3.24,0.30,2.81,5.68,1.03,3.17,1185.0
3,14.37,1.95,2.50,16.8,113.0,3.85,3.49,0.24,2.18,7.80,0.86,3.45,1480.0
4,13.24,2.59,2.87,21.0,118.0,2.80,2.69,0.39,1.82,4.32,1.04,2.93,735.0

In [78]:
wine.target_names

array(['class_0', 'class_1', 'class_2'], dtype='<U7')

In [79]:
wine.target

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2])

In [80]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(wine.data, wine.target, test_size=0.25)

In [81]:
x_train

array([[1.438e+01, 3.590e+00, 2.280e+00, ..., 1.040e+00, 3.440e+00,
        1.065e+03],
       [1.330e+01, 1.720e+00, 2.140e+00, ..., 1.020e+00, 2.770e+00,
        1.285e+03],
       [1.305e+01, 2.050e+00, 3.220e+00, ..., 1.130e+00, 3.200e+00,
        8.300e+02],
       ...,
       [1.237e+01, 1.130e+00, 2.160e+00, ..., 1.220e+00, 2.870e+00,
        4.200e+02],
       [1.311e+01, 1.010e+00, 1.700e+00, ..., 1.120e+00, 3.180e+00,
        5.020e+02],
       [1.336e+01, 2.560e+00, 2.350e+00, ..., 7.000e-01, 2.470e+00,
        7.800e+02]], shape=(133, 13))

In [82]:
x_test

array([[1.270e+01, 3.550e+00, 2.360e+00, 2.150e+01, 1.060e+02, 1.700e+00,
        1.200e+00, 1.700e-01, 8.400e-01, 5.000e+00, 7.800e-01, 1.290e+00,
        6.000e+02],
       [1.264e+01, 1.360e+00, 2.020e+00, 1.680e+01, 1.000e+02, 2.020e+00,
        1.410e+00, 5.300e-01, 6.200e-01, 5.750e+00, 9.800e-01, 1.590e+00,
        4.500e+02],
       [1.179e+01, 2.130e+00, 2.780e+00, 2.850e+01, 9.200e+01, 2.130e+00,
        2.240e+00, 5.800e-01, 1.760e+00, 3.000e+00, 9.700e-01, 2.440e+00,
        4.660e+02],
       [1.176e+01, 2.680e+00, 2.920e+00, 2.000e+01, 1.030e+02, 1.750e+00,
        2.030e+00, 6.000e-01, 1.050e+00, 3.800e+00, 1.230e+00, 2.500e+00,
        6.070e+02],
       [1.282e+01, 3.370e+00, 2.300e+00, 1.950e+01, 8.800e+01, 1.480e+00,
        6.600e-01, 4.000e-01, 9.700e-01, 1.026e+01, 7.200e-01, 1.750e+00,
        6.850e+02],
       [1.311e+01, 1.900e+00, 2.750e+00, 2.550e+01, 1.160e+02, 2.200e+00,
        1.280e+00, 2.600e-01, 1.560e+00, 7.100e+00, 6.100e-01, 1.330e+00,
        4.250e+02],
       [1.305e+01, 5.800e+00, 2.130e+00, 2.150e+01, 8.600e+01, 2.620e+00,
        2.650e+00, 3.000e-01, 2.010e+00, 2.600e+00, 7.300e-01, 3.100e+00,
        3.800e+02],
       [1.305e+01, 3.860e+00, 2.320e+00, 2.250e+01, 8.500e+01, 1.650e+00,
        1.590e+00, 6.100e-01, 1.620e+00, 4.800e+00, 8.400e-01, 2.010e+00,
        5.150e+02],
       [1.220e+01, 3.030e+00, 2.320e+00, 1.900e+01, 9.600e+01, 1.250e+00,
        4.900e-01, 4.000e-01, 7.300e-01, 5.500e+00, 6.600e-01, 1.830e+00,
        5.100e+02],
       [1.296e+01, 3.450e+00, 2.350e+00, 1.850e+01, 1.060e+02, 1.390e+00,
        7.000e-01, 4.000e-01, 9.400e-01, 5.280e+00, 6.800e-01, 1.750e+00,
        6.750e+02],
       [1.387e+01, 1.900e+00, 2.800e+00, 1.940e+01, 1.070e+02, 2.950e+00,
        2.970e+00, 3.700e-01, 1.760e+00, 4.500e+00, 1.250e+00, 3.400e+00,
        9.150e+02],
       [1.421e+01, 4.040e+00, 2.440e+00, 1.890e+01, 1.110e+02, 2.850e+00,
        2.650e+00, 3.000e-01, 1.250e+00, 5.240e+00, 8.700e-01, 3.330e+00,
        1.080e+03],
       [1.184e+01, 2.890e+00, 2.230e+00, 1.800e+01, 1.120e+02, 1.720e+00,
        1.320e+00, 4.300e-01, 9.500e-01, 2.650e+00, 9.600e-01, 2.520e+00,
        5.000e+02],
       [1.340e+01, 3.910e+00, 2.480e+00, 2.300e+01, 1.020e+02, 1.800e+00,
        7.500e-01, 4.300e-01, 1.410e+00, 7.300e+00, 7.000e-01, 1.560e+00,
        7.500e+02],
       [1.372e+01, 1.430e+00, 2.500e+00, 1.670e+01, 1.080e+02, 3.400e+00,
        3.670e+00, 1.900e-01, 2.040e+00, 6.800e+00, 8.900e-01, 2.870e+00,
        1.285e+03],
       [1.141e+01, 7.400e-01, 2.500e+00, 2.100e+01, 8.800e+01, 2.480e+00,
        2.010e+00, 4.200e-01, 1.440e+00, 3.080e+00, 1.100e+00, 2.310e+00,
        4.340e+02],
       [1.327e+01, 4.280e+00, 2.260e+00, 2.000e+01, 1.200e+02, 1.590e+00,
        6.900e-01, 4.300e-01, 1.350e+00, 1.020e+01, 5.900e-01, 1.560e+00,
        8.350e+02],
       [1.410e+01, 2.160e+00, 2.300e+00, 1.800e+01, 1.050e+02, 2.950e+00,
        3.320e+00, 2.200e-01, 2.380e+00, 5.750e+00, 1.250e+00, 3.170e+00,
        1.510e+03],
       [1.390e+01, 1.680e+00, 2.120e+00, 1.600e+01, 1.010e+02, 3.100e+00,
        3.390e+00, 2.100e-01, 2.140e+00, 6.100e+00, 9.100e-01, 3.330e+00,
        9.850e+02],
       [1.182e+01, 1.720e+00, 1.880e+00, 1.950e+01, 8.600e+01, 2.500e+00,
        1.640e+00, 3.700e-01, 1.420e+00, 2.060e+00, 9.400e-01, 2.440e+00,
        4.150e+02],
       [1.164e+01, 2.060e+00, 2.460e+00, 2.160e+01, 8.400e+01, 1.950e+00,
        1.690e+00, 4.800e-01, 1.350e+00, 2.800e+00, 1.000e+00, 2.750e+00,
        6.800e+02],
       [1.166e+01, 1.880e+00, 1.920e+00, 1.600e+01, 9.700e+01, 1.610e+00,
        1.570e+00, 3.400e-01, 1.150e+00, 3.800e+00, 1.230e+00, 2.140e+00,
        4.280e+02],
       [1.340e+01, 4.600e+00, 2.860e+00, 2.500e+01, 1.120e+02, 1.980e+00,
        9.600e-01, 2.700e-01, 1.110e+00, 8.500e+00, 6.700e-01, 1.920e+00,
        6.300e+02],
       [1.483e+01, 1.640e+00, 2.170e+00, 1.400e+01, 9.700e+01, 2.800e+00,
        2.980e+00, 2.900e-01, 1.980e+00, 5.200e+00, 1.080e+00, 2.850e+00,
        1.045e+03],
       [1.287e+01, 4.610e+00, 2.480e+00, 2.150e+01, 8.600e+01, 1.700e+00,
        6.500e-01, 4.700e-01, 8.600e-01, 7.650e+00, 5.400e-01, 1.860e+00,
        6.250e+02],
       [1.350e+01, 3.120e+00, 2.620e+00, 2.400e+01, 1.230e+02, 1.400e+00,
        1.570e+00, 2.200e-01, 1.250e+00, 8.600e+00, 5.900e-01, 1.300e+00,
        5.000e+02],
       [1.222e+01, 1.290e+00, 1.940e+00, 1.900e+01, 9.200e+01, 2.360e+00,
        2.040e+00, 3.900e-01, 2.080e+00, 2.700e+00, 8.600e-01, 3.020e+00,
        3.120e+02],
       [1.285e+01, 3.270e+00, 2.580e+00, 2.200e+01, 1.060e+02, 1.650e+00,
        6.000e-01, 6.000e-01, 9.600e-01, 5.580e+00, 8.700e-01, 2.110e+00,
        5.700e+02],
       [1.332e+01, 3.240e+00, 2.380e+00, 2.150e+01, 9.200e+01, 1.930e+00,
        7.600e-01, 4.500e-01, 1.250e+00, 8.420e+00, 5.500e-01, 1.620e+00,
        6.500e+02],
       [1.258e+01, 1.290e+00, 2.100e+00, 2.000e+01, 1.030e+02, 1.480e+00,
        5.800e-01, 5.300e-01, 1.400e+00, 7.600e+00, 5.800e-01, 1.550e+00,
        6.400e+02],
       [1.348e+01, 1.670e+00, 2.640e+00, 2.250e+01, 8.900e+01, 2.600e+00,
        1.100e+00, 5.200e-01, 2.290e+00, 1.175e+01, 5.700e-01, 1.780e+00,
        6.200e+02],
       [1.419e+01, 1.590e+00, 2.480e+00, 1.650e+01, 1.080e+02, 3.300e+00,
        3.930e+00, 3.200e-01, 1.860e+00, 8.700e+00, 1.230e+00, 2.820e+00,
        1.680e+03],
       [1.388e+01, 1.890e+00, 2.590e+00, 1.500e+01, 1.010e+02, 3.250e+00,
        3.560e+00, 1.700e-01, 1.700e+00, 5.430e+00, 8.800e-01, 3.560e+00,
        1.095e+03],
       [1.394e+01, 1.730e+00, 2.270e+00, 1.740e+01, 1.080e+02, 2.880e+00,
        3.540e+00, 3.200e-01, 2.080e+00, 8.900e+00, 1.120e+00, 3.100e+00,
        1.260e+03],
       [1.182e+01, 1.470e+00, 1.990e+00, 2.080e+01, 8.600e+01, 1.980e+00,
        1.600e+00, 3.000e-01, 1.530e+00, 1.950e+00, 9.500e-01, 3.330e+00,
        4.950e+02],
       [1.376e+01, 1.530e+00, 2.700e+00, 1.950e+01, 1.320e+02, 2.950e+00,
        2.740e+00, 5.000e-01, 1.350e+00, 5.400e+00, 1.250e+00, 3.000e+00,
        1.235e+03],
       [1.351e+01, 1.800e+00, 2.650e+00, 1.900e+01, 1.100e+02, 2.350e+00,
        2.530e+00, 2.900e-01, 1.540e+00, 4.200e+00, 1.100e+00, 2.870e+00,
        1.095e+03],
       [1.293e+01, 3.800e+00, 2.650e+00, 1.860e+01, 1.020e+02, 2.410e+00,
        2.410e+00, 2.500e-01, 1.980e+00, 4.500e+00, 1.030e+00, 3.520e+00,
        7.700e+02],
       [1.434e+01, 1.680e+00, 2.700e+00, 2.500e+01, 9.800e+01, 2.800e+00,
        1.310e+00, 5.300e-01, 2.700e+00, 1.300e+01, 5.700e-01, 1.960e+00,
        6.600e+02],
       [1.237e+01, 1.070e+00, 2.100e+00, 1.850e+01, 8.800e+01, 3.520e+00,
        3.750e+00, 2.400e-01, 1.950e+00, 4.500e+00, 1.040e+00, 2.770e+00,
        6.600e+02],
       [1.225e+01, 4.720e+00, 2.540e+00, 2.100e+01, 8.900e+01, 1.380e+00,
        4.700e-01, 5.300e-01, 8.000e-01, 3.850e+00, 7.500e-01, 1.270e+00,
        7.200e+02],
       [1.288e+01, 2.990e+00, 2.400e+00, 2.000e+01, 1.040e+02, 1.300e+00,
        1.220e+00, 2.400e-01, 8.300e-01, 5.400e+00, 7.400e-01, 1.420e+00,
        5.300e+02],
       [1.242e+01, 4.430e+00, 2.730e+00, 2.650e+01, 1.020e+02, 2.200e+00,
        2.130e+00, 4.300e-01, 1.710e+00, 2.080e+00, 9.200e-01, 3.120e+00,
        3.650e+02],
       [1.438e+01, 1.870e+00, 2.380e+00, 1.200e+01, 1.020e+02, 3.300e+00,
        3.640e+00, 2.900e-01, 2.960e+00, 7.500e+00, 1.200e+00, 3.000e+00,
        1.547e+03],
       [1.363e+01, 1.810e+00, 2.700e+00, 1.720e+01, 1.120e+02, 2.850e+00,
        2.910e+00, 3.000e-01, 1.460e+00, 7.300e+00, 1.280e+00, 2.880e+00,
        1.310e+03]])

In [83]:
clf = Pipeline([
    ('nb', MultinomialNB())
])

In [84]:
clf.fit(x_train, y_train)

Pipeline(steps=[('nb', MultinomialNB())])

In [85]:
clf.score(x_test,y_test)

0.8888888888888888

In [86]:
clf1 = Pipeline([
    ('nb', GaussianNB())
])

In [87]:
clf1.fit(x_train,y_train)

Pipeline(steps=[('nb', GaussianNB())])

In [88]:
clf1.score(x_test, y_test)

0.9777777777777777

In [89]:
len(x_test)

45

In [90]:
len(x_train)

133